cors:
  origin:
    - http://localhost:8080

mbtiles:
  paths:
    - /tiles

# pmtiles:
#   paths:
#     - /tiles

sprites:
  paths:
    - /sprites/liberty
    - /sprites/liberty-dark
    - /sprites/dark

fonts:
  - /fonts

styles:
   paths:
     - /styles
