server {
    listen 80;
    server_name _;

    client_max_body_size 20m;
    sendfile on;
    tcp_nopush on;
    aio on;

    location /asset/ {
        proxy_pass http://host.docker.internal:53964/api/v1/asset/; #backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /protected-assets/ {
        internal;
        alias /var/www/assets/;
        add_header Accept-Ranges bytes always;
        add_header Access-Control-Expose-Headers "Content-Length,Content-Range,Accept-Ranges" always;
        types {
            video/mp4 mp4;
            video/quicktime mov;
            image/jpeg jpg jpeg;
            image/png png;
            image/webp webp;
        }
        default_type application/octet-stream;
        expires 30d;
        access_log off;
    }

    location / {
        return 404;
    }
}