name: "Build and publish apk"

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get current tag
        id: get-tag
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          VERSION_TAG=${FULL_TAG#v}
          echo "version_tag=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "Version Tag: ${VERSION_TAG}"

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install Dependencies
        working-directory: frontend
        run: flutter pub get
        
      - name: Build APK
        working-directory: frontend
        run: |
          VERSION_TAG='${{ steps.get-tag.outputs.version_tag }}'
          flutter build apk --release --split-per-abi --build-name="$VERSION_TAG" --build-number="${GITHUB_RUN_NUMBER}"

      - name: Prepare Release Artifacts
        working-directory: frontend
        run: |
          VERSION_TAG='${{ steps.get-tag.outputs.version_tag }}'
          SOURCE_APK='build/app/outputs/flutter-apk/app-arm64-v8a-release.apk'
          RELEASE_APK="build/app/outputs/flutter-apk/serpa-maps-${VERSION_TAG}-arm64.apk"
          RELEASE_SHA1="${RELEASE_APK}.sha1"

          cp "$SOURCE_APK" "$RELEASE_APK"
          sha1sum "$RELEASE_APK" | awk '{print $1}' > "$RELEASE_SHA1"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            frontend/build/app/outputs/flutter-apk/serpa-maps-${{ steps.get-tag.outputs.version_tag }}-arm64.apk
            frontend/build/app/outputs/flutter-apk/serpa-maps-${{ steps.get-tag.outputs.version_tag }}-arm64.apk.sha1

      - name: Update Release Assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            frontend/build/app/outputs/flutter-apk/serpa-maps-${{ steps.get-tag.outputs.version_tag }}-arm64.apk
            frontend/build/app/outputs/flutter-apk/serpa-maps-${{ steps.get-tag.outputs.version_tag }}-arm64.apk.sha1
          replacesArtifacts: true
          tag: v${{ steps.get-tag.outputs.version_tag }}
